/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lishui_example_app_test_JniTest */

#ifndef _Included_lishui_example_app_test_JniTest
#define _Included_lishui_example_app_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lishui_example_app_test_JniTest
 * Method:    getNativeStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lishui_example_app_test_JniTest_getNativeStr
  (JNIEnv *, jobject);

/*
 * Class:     lishui_example_app_test_JniTest
 * Method:    setNativeStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lishui_example_app_test_JniTest_setNativeStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
